version: "3.1"
services:
  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - ./dbdata:/data/db
    # ports:
     # - 27017:27017
   
  my-app:
    image: my-app:v1
    build: .
    environment: 
       SPRING_APPLICATION_JSON: '{"spring":{ "data": { "mongodb": {  "uri": "mongodb://mongo/test"}}}, "logging": { "level": { "org": { "springframework": { "web": "DEBUG"}}}}}'
    depends_on:
      - mongo

  proxy:
    image: nginx:stable-alpine
    ports:
     - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d:ro
    depends_on:
      - my-app